### ISSUE TITLE
LoadDevicesAsync Error

### ISSUE THREAD

**Issue by jgassens** [hsakoh/switchbot-mqtt#10]
Everything starts—all services start but fetching devices doesn’t do anything. Logs show devices are found but ends in the titular error. Not sure what to do now…

![IMG_3306](https://github.com/hsakoh/switchbot-mqtt/assets/104028936/e34f42c5-f9a4-46c8-a599-bdb45d5b4d48)

**Comment by hsakoh** [comment]
As far as I can see from the screenshot,
`E2F67EBAEBE4`,`EB7E2015D93D` is due to the fact that the device type of the device is unknown.

Please refer to the following issue. 
#3 
It seems that some devices, such as Curtain 3, are not returning DeviceType as per the API interface specifications. 

Please try defining the device ID and device type in the EnforceDeviceTypes option.

**Comment by jgassens** [comment]
Thanks! I've done that per the example you posted but it won't let me save the configuration file. It gives the error below again:
<img width="1010" alt="Screenshot 2023-12-24 at 12 46 59 PM" src="https://github.com/hsakoh/switchbot-mqtt/assets/104028936/2f534c4b-127f-45b4-834b-97f95dfed207">

Just in case i've got the syntax wrong here's what i've entered:
<img width="577" alt="Screenshot 2023-12-24 at 12 46 54 PM" src="https://github.com/hsakoh/switchbot-mqtt/assets/104028936/3552f2c2-5c20-446b-8aef-386dce167cb7">

**Comment by jgassens** [comment]
I put the below in and I get an error that doesn't allow me to save my config file
<img width="577" alt="Screenshot 2023-12-24 at 12 46 54 PM" src="https://github.com/hsakoh/switchbot-mqtt/assets/104028936/948dfb7e-27df-4722-be73-d901e2c76cf0">

I get this:

<img width="1416" alt="Screenshot 2023-12-24 at 12 50 15 PM" src="https://github.com/hsakoh/switchbot-mqtt/assets/104028936/750dcd5c-f79c-439c-ad40-debf6d12bf2d">

**Comment by hsakoh** [comment]
UI
![image](https://github.com/hsakoh/switchbot-mqtt/assets/20980395/dda9dfa9-2eb2-495d-a7e2-a1f81b07a768)

YAML Editor
```
EnforceDeviceTypes:
  - DeviceId: E2F67EBAEBE4
    DeviceType: Curtain
  - DeviceId: EB7E2015D93D
    DeviceType: Curtain
```

**Comment by jgassens** [comment]
Once again, thank you so much! I have four of those Curtian V3's that were giving me trouble. All working now. You totally rock.
