### ISSUE TITLE
Question about tilt cam

### ISSUE THREAD

**Issue by giobuc** [hsakoh/switchbot-mqtt#16]
Thank's for your job 🙂
I'm not a Home Assistant expert, I hope I'm not asking a silly question.
I think I installed everything correctly, I have Mosquito active and Ngrok Authkey inserted.
I correctly see the list of my Switchbot devices, both physical and virtual ones.
Among these I have numerous tilt cams.
Is it possible to view cam images in real time or at intervals?
Or can I just get string information from them?
Thank you :)

![Schermata 2024-03-01 08 20 04](https://github.com/hsakoh/switchbot-mqtt/assets/50290058/48c12d84-70cb-4a6d-aa3a-f29a18ed9a08)

**Comment by hsakoh** [comment]
Thanks for giving the add-on a try!

Unfortunately, as of now, we can't fetch the latest image or its URL for the Pan/Tilt Cam through the API, so I can't fulfill your request.

Firstly, I recommend expressing your feature request for functionality expansion on the [SwitchBot API](https://github.com/OpenWonderLabs/SwitchBotAPI).
