### ISSUE TITLE
Ceiling Light ProのPowerStatusが正しく反映されない

### ISSUE THREAD

**Issue by hirocho-t** [hsakoh/switchbot-mqtt#25]
MqttCoreServiceのstart時とwebhookの受信時に正しく反映されないのですが、仕様上仕方がないものでしょうか？

添付画像1はCeiling Light Proで最後のbrightnessが59の状態でOFFにした状態から、下記の1,2を実行したものです。
1.純正リモコンのON/OFFボタンを押してONにした。
2.純正リモコンの「明るい」ボタンを押して明るくした（内部的にはbrightnessが77に変更）
![添付画像1](https://github.com/hsakoh/switchbot-mqtt/assets/135151501/b6258d78-dd70-4fa6-b47d-97d4975cafbf)
webhookのログからpowerStateの値がONになっているのに画面上ではクリアのまま変わりません。brightnessは59から77に変わりました。

また画面上のPollingの「押す」を押すと正しく反映されます。（添付画像2）
![添付画像2](https://github.com/hsakoh/switchbot-mqtt/assets/135151501/a4674302-10e4-44da-826b-77b2f596a4aa)

**Comment by hsakoh** [comment]
アドオンのv1.0.15以前のマスタ定義に誤りがありました。
具体的には、シーリングライトProの センサー powerが、statusAPIのみを参照し、webhookを参照しないという設定になってました。
これはv1.0.16にて修正されています。

デバイス取得時にマスタデータを個別の内部デバイスデータとして永続化するつくりのため、
v1.0.15以前にデバイスを取得し構成していた場合、マスタの変更が個別の内部デバイスデータに反映されません。
そのためWebhookを受信しても、MQTTメッセージに送信されないという事象が発生していると思われます。

リリースノートには記載しましたが、
1. MQTT デバイスを一度 削除
1. Ingress ページでデバイスを削除・再取得・再構成
1. アドオンを再起動
で改善されると思います。

今回のケースでは1.は不要と思いますが、もし 2.～3. を行って改善しない場合、1.～3.の順序で試してみてください。

**Comment by hirocho-t** [comment]
数日前に追加されたarmv7:1.0.17でraspbianにdockerで昨日構築が完了した環境になります(環境構築ができるまでの推移は某掲示板で見ていただけたのかと思います)

指示された1.～3.の手順に該当すると思われる操作を下記のように実行しましたが現象は変わりませんでした。

1.MQTT Explorerを使いhomeassistant/<component>/*Ceiling Light ProのデバイスID*となっているTopicをすべて削除し、MQTT統合から削除されたのを確認しました。
2.SwitchBotMqttAppからMqttCoreService、WebhookServiceをStopし、「Fetch Devices by SwitchBotAPI」を押し、一旦すべてのチェックを外しSaveし、改めてCeiling Light Proにチェックをしました。
3.docker containerを再起動し、SwitchBotMqttAppからMqttCoreService、WebhookServiceをStartさせました。

必要なログの取り方がわからないので教えていただけますでしょうか？
_docker-compose\options.jsonのLogLevelをdebugにしてみたのですがどこにログがあるのかわかりませんでした。

**Comment by hsakoh** [comment]
> 必要なログの取り方がわからないので教えていただけますでしょうか？

options.jsonのLogLevelを`Trace`に設定していただければ出力が増えるかと思います。(`Verbose`は誤りでした)
(DockerComposeであれば、出力先はコンテナのログとなるかと思います。
　最初に貼っていただいたスクリーンショットと同じところです。

また、原因が分かりました。
WebhookとStatusAPIの値に大文字小文字の差異があり、MQTT統合がケースセンシティブであったためです。

Webhookの場合、`powerState`:`ON`または`OFF`
StatusAPIの場合、`power`:`on`または`off`

MQTT統合としては、MQTTトピック：`homeassistant/binary_sensor/both_power_デバイスID/config`を確認いただければわかると思いますが、小文字を設定していました。
payload_on: 'on'
payload_off: 'off'

問題の事象のような、StatusAPI、Webhook両方に値が存在し、具体値が(SwitchBotの仕様上)異なるケースについて、値を小文字化して送信するよう変更しました。
（MQTTトピック：`switchbot/デバイスID/status/both`に送る値）

修正し、v1.0.18を先ほどリリースしましたので、そちらで確認ください。

**Comment by hirocho-t** [comment]
switchbot-mqtt起動時にON/OFF状態、純正リモコンによるON/OFFによるwebhookの反映は正しく動くようになりました。ありがとうございます。

しかし、まだよくわからない動きがあります。
Ceiling Light Proが点灯の状態でswitchbot-mqtt起動しました。
起動後powerは「検出されました」で正しいです。
そこでturnOffボタンを押します。
commandがPOSTされ、実際に消灯しますが、webhookでoffのログが出力されず、powerは「検出されました」のままになります。

そのままtrunOnボタンを押します。
commandがPOSTされ、実際に点灯します。webohookはなぜかoffのログが出力され、powerは「クリア」になります。
（添付画像3 緑色がturnOff、水色がturnOnです）
![添付画像3](https://github.com/hsakoh/switchbot-mqtt/assets/135151501/c58254b2-44ed-4a9f-b1f2-2017d9c66a7a)

試しているときにはoffに続けてonのwebhookのログが連続して出力される事もありました。switchbot API側の問題のような気もします。

**Comment by hsakoh** [comment]
追記です。

ColorBulbでも数回 試しましたが、
　SwitchBotAPIで操作した場合、Webhookが届かず
　スマートフォンアプリで操作した場合、Webhookが届く
という様な挙動をしています。

APIで操作した場合も（Webhookを受信するアプリが異なる可能性があるので、）
常に送信される事が当然の期待値なのですが…

もしかしたらシーリングライトも同様の振舞いかもしれません。
純正リモコン・スマートフォンアプリ・SwitchBotAPIそれぞれで、
（Webhookの遅延を排除する為） 1，2分程度時間をあけつつ操作して、どうなるか 見てみたい所です。

（PlugMiniも再確認しましたが、SwitchBotAPIで操作してもWebhookは必ず来ます。）

**Comment by hirocho-t** [comment]
やはりSwitchbot側の問題っぽいですね。
一時的な問題なのか様子を見つつ、ステータスがズレても問題のない運用をしようと思います。
ありがとうございました。
