### ISSUE TITLE
Cannot lock/unlock the Switchbot Lock Pro

### ISSUE THREAD

**Issue by astumpf** [hsakoh/switchbot-mqtt#29]
Lock status is retrieved without issues, but execution of lock/unlock commands are failing, see screenshot

![Unbenannt](https://github.com/user-attachments/assets/b5ab2cbc-a81e-4c79-87aa-c3dc32e56cec)

PS: I removed the DeviceID from the screenshot ;-).

**Comment by hsakoh** [comment]
https://github.com/OpenWonderLabs/SwitchBotAPI/issues/317

**Comment by astumpf** [comment]
Thanks for the reference!
