### ISSUE TITLE
Security concerns using ngrok webhooks -> unprotected, public accessible switchbot-mqtt interface

### ISSUE THREAD

**Issue by astumpf** [hsakoh/switchbot-mqtt#30]
Following the provided install instructions leaves you with an unprotected ngrok reverse proxy, e.g. https://yyyy-xxx-xxx-xxx-xxx.ngrok-free.app, where yyyy ist the instance id and xxx-xxx-xxx-xxx is your (router's) public ip. So there is already a fair chance to guess the link.  This provides intruders an easy door to get full access to your Switchbot devices, which can especially include doorlocks. The redirected switchbot-mqtt page is publicly accessible including all controls!

This is a serious security issue that I would like to address here. As I am not familiar with the (free) ngrok services, I would like to ask if there are ways to improve this and include proper instructions in the installation guide to close this vulnerability.

**Comment by hsakoh** [comment]
Thank you for pointing that out.

I initially intended to block access to the Ingress page. However, due to an error in the port number passed to Ngrok, it was inadvertently exposed.

The issue has been fixed, and version v1.0.19 has just been released.

**Comment by astumpf** [comment]
Thanks for quick reaction 👍
