### ISSUE TITLE
Error testing commands with Switchbot curtain 3

### ISSUE THREAD

**Issue by Sugarretan** [hsakoh/switchbot-mqtt#32]
I get the following error while testing the commands of the Switchbot curtain 3 (open/close...):

{"statusCode":171,"body":{},"message":"Cannot get the status of device"}.

My config is the following:

AutoConfig: true
Host: ""
Port: 1883
Id: ""
Pw: ""
Tls: false

UseWebhook: true
UseNgrok: false
NgrokAuthToken: <Configuration required only when using Webhook with ngrok>
HostUrl: http://homeassistant:8098

The Apikey & Apisecret seem to be OK.

**Comment by hsakoh** [comment]
This information alone doesn't quite explain the cause. Please set the log level to Trace, restart the add-on, and provide the logs when the issue occurs again.

By the way, is the cloud service for the curtain enabled? This is the operation in Step 1 on the following page.
https://support.switch-bot.com/hc/en-us/articles/360052804914-How-to-control-your-Curtain-with-IFTTT

**Comment by Sugarretan** [comment]
Sorry, I didn`t know that the cloud service had to be enabled and so the hub was needed. The hub mini would do the job then?

Thanks

**Comment by hsakoh** [comment]
In my environment, I can confirm that both Hub Mini and Hub 2 appear as candidates.
