### ISSUE TITLE
Missing config file in HowToInstall guide

### ISSUE THREAD

**Issue by MichDem** [hsakoh/switchbot-mqtt#49]
Following the [https://github.com/hsakoh/switchbot-mqtt/wiki/HowToInstall](HowToInstall) guide, I got to the section, when I was supposed to enter SwitchBot ApiKey and ApiSecret into a yaml file, however it is not specified, which file.

I assumed it was `configuration.yaml`, but putting it there resulted in a warning about not recognizing `SwtichBot` service.

I'd propose to include the full paths to files in the guide, which need to be edited

**Comment by hsakoh** [comment]
This is a Home Assistant add-on.
It is not something configured through the configuration.yaml as it is not a Home Assistant service.

If you have installed it as a Home Assistant add-on, the configuration screen is located at `http://<haos>:8123/hassio/addon/cafb8c58_switchbot_mqtt/config`

**Comment by MichDem** [comment]
Ah, I see. I have it installed as HA add-on, so aside from `hassio/addon/cafb8c58_switchbot_mqtt/config` endpoint I can reach it also via Settings -> Add-ons -> SwitchBot-Mqtt -> Configuration.

Any chance to include that in the instruction as well? Cause as you can see, I didn't figured it out by myself, and there might be others in a similar situation as I. Thanks in advance.

**Comment by hsakoh** [comment]
The application is an add-on, and it is self-evident that its configuration can be done from the add-on's settings page. Therefore, we currently have no plans to add such redundant descriptions.
