### ISSUE TITLE
Configuring the webhook service to receive traffic via a reverse proxy

### ISSUE THREAD

**Issue by hunterdrayman** [hsakoh/switchbot-mqtt#50]
I have a question about the Webhook service config, please.

My HA host running the add-on is on an internal server which is not internet addressable (192.168.x.x). I use Traefik reverse proxy to manage all incoming traffic. So I have set up a Traefik router to forward https://my-webhooks.my.domain to http://192.168.x.x:8098 and I have configured the add-on as follows:

> UseWebhook: true
UseNgrok: false
NgrokAuthToken: \<Configuration required only when using Webhook with ngrok\>
HostUrl: https://my-webhooks.my.domain

In the docs it states:

> Add-on itself will listen for requests at http://\<your public ip address\>:8098/webhook.

Should I expect this to work? I don't see any traffic arrive at 192.168.x.x

Thanks

**Comment by hsakoh** [comment]
Yes. That's the right setup.

**Comment by hsakoh** [comment]
As part of troubleshooting, please first check if the addon is able to listen for Webhooks.

URL: http://192.168.x.x:8098/webhook
Method: POST
Content-Type: application/json
Body:
```
{"eventType":"changeReport","eventVersion":"1","context":{"deviceType":"WoCurtain","deviceMac":"FFF921xxxx","calibrate":true,"group":false,"slidePosition":100,"battery":99,"timeOfSample":1715158038876}}
```
If webhooks can be invoked, you'll see logs like the following:

For an unknown device ID:

```
warn: SwitchBotMqttApp.Services.MqttCoreService[0] unknown deviceMac FFF921xxxx
```

**Comment by hunterdrayman** [comment]
Thanks for the confirmation. I tried your test and it worked - and also the API webhooks are now arriving so I must have misinterpreted the log earlier or something has reset in the proxy.

The log is now showing my two robots belting away. Interestingly the workingStatus of one is "Clearing" when it probably should be "Cleaning".

> 13:29:05 info: SwitchBotMqttApp.Controllers.WebhookController[0] {"eventType":"changeReport","eventVersion":"1","context":{"deviceType":"Robot Vacuum Cleaner S10","deviceMac":"xxxxxxxxx","timeOfSample":1728390545483},"onlineStatus":"online","workingStatus":"Clearing","waterBaseBattery":91}
