### ISSUE TITLE
[Question] Auto Start services in standalone mode?

### ISSUE THREAD

**Issue by thomas41587** [hsakoh/switchbot-mqtt#55]
I am using this really cool Switchbot integration as standalone solution in a docker environment. In Home Assistant it was possible to activate a "AutoStartServices" option. How can I do that for a usual docker container? Restarting the container always stops all three services and I have to manually start them :-(

**Comment by hsakoh** [comment]
I believe it is running based on the Docker Compose in the following Wiki, and it should work by setting the boolean value on the third line of `options.json` to `true`.
Or are you saying that the setting does not work?

https://github.com/hsakoh/switchbot-mqtt/wiki/HowToInstall#running-as-an-independent-docker-container
https://github.com/hsakoh/switchbot-mqtt/blob/main/_docker-compose/options_Example.json#L3

**Comment by thomas41587** [comment]
Thank you for pointing me towards this really obvious options. Seems like I missed that at least twice when looking for the the available options :-(
This option of course did the trick. Setting it to true makes the services start automatically!
