### ISSUE TITLE
Contact Sensor Button

### ISSUE THREAD

**Issue by giantsfan006** [hsakoh/switchbot-mqtt#56]
Just wondering if I've missed something but I've got the Add-on all set up and HA is getting state changes but and there doesn't appear to be any functionality for a button press. Is that just a limitation or did I screw up somewhere?

**Comment by hsakoh** [comment]
Which of the following "buttons" are you referring to?  
- The physical button on the Contact Sensor  
- The Polling button detected via MQTT Discovery on Home Assistant  

**Regarding the former:**  
I’ve read the manual for that button, but it doesn’t seem to have any specific function.  

**If it’s the latter:**  
Pressing the button retrieves information from the server and updates the status.  
(You can retrieve `battery`, `moveDetected`, `openState`, and `brightness` information.  
[https://github.com/OpenWonderLabs/SwitchBotAPI#contact-sensor-1](https://github.com/OpenWonderLabs/SwitchBotAPI#contact-sensor-1))  

Additionally, this add-on supports receiving webhooks for the Contact Sensor.  
[https://github.com/OpenWonderLabs/SwitchBotAPI#contact-sensor-2](https://github.com/OpenWonderLabs/SwitchBotAPI#contact-sensor-2)  
This occurs when open/close detection or motion detection is triggered.  

What exactly do you mean by "doesn't appear to be any functionality"?  
What were you expecting, and what specific results are not being achieved?

**Comment by giantsfan006** [comment]
I'm referring to the physical button on the device. I would expect it to be an entity in Home Assistant that, when pressed, could trigger an automation. That's what it does in the switchbot app.

**Comment by hsakoh** [comment]
First of all, I don’t believe that such a feature is implemented in the Contact Sensor.

The manual mentions the physical button as a “Fresnel Lens & Reset Button.”
https://drive.google.com/file/d/1vrWBxr_C3LJwOR9HWbOk8wT9qXzZtK_D/view

From the teardown photos, it appears that there is a function for emitting infrared for motion detection and a button for resetting.
https://fcc.report/FCC-ID/2AKXB-W1201500/5257863

I also couldn’t find any description in the SwitchBot Help Center indicating that pressing the button could trigger any specific action.
There is no mention in the API or Webhook documentation that pressing the button sends a webhook or performs any such function.

Therefore, it is not possible for this add-on to trigger events in Home Assistant or change states when the physical button is pressed.

**Comment by hsakoh** [comment]
There’s one thing I hadn’t fully understood.

In the SwitchBot app, it seems there is an automation trigger for the Contact Sensor’s button press event (I wasn’t aware of this).

However, I have confirmed that pressing the button does not currently trigger a webhook.
Therefore, there’s still nothing that this add-on can do in its current state.

I think it would be a good idea to request that webhook functionality be added in the API repository:
https://github.com/OpenWonderLabs/SwitchBotAPI

If webhook functionality is added, the add-on can then be updated to support it.

**Comment by giantsfan006** [comment]
Gotcha. There's an open issue for it but it's 3 years old with no interaction from the developers.

https://github.com/OpenWonderLabs/SwitchBotAPI/issues/62

Which is a shame since it was a deciding factor when I purchased these things.

Thanks for your help!
