### ISSUE TITLE
Retain flag and QoS for MQTT messages

### ISSUE THREAD

**Issue by hunterdrayman** [hsakoh/switchbot-mqtt#58]
This is really a request for comment with possible implementation if viable.

Having built some automations in node-RED triggered by webhooks, I'm having issues on node-RED startup because the state of my vacs aren't known until they do something. I'm thinking that a possible solution is for switchbott-mqtt to be configurable to set the RETAIN flag when publishing some mqtt packets. Maybe QoS could be specified too?

If not suitable, I can probably contrive to store state in node-RED persistent storage, but I thought I'd ask the question.

**Comment by hsakoh** [comment]
Add-ons are primarily designed for Home Assistant's MQTT integration. As such, it is expected that entity messages are implemented with retain enabled, while state messages are implemented with retain disabled.
For more details, refer to the documentation:
Home Assistant MQTT Integration - Using Retained Config Messages

While we see limited benefits in making the retain behavior configurable, we have released version v1.0.30, which allows retain settings to be changed.
If you wish to make QoS configurable as well, please refer to these changes and modify your application accordingly.
