### ISSUE TITLE
failure when creating new passcode

### ISSUE THREAD

**Issue by marcomow** [hsakoh/switchbot-mqtt#6]
I'm using the `createKey` command in the MQTT device dashboard
![image](https://github.com/hsakoh/switchbot-mqtt/assets/4977000/0e8d35d8-6e7c-4a29-8dd9-5173abc89936)

but the command fails, see the following logs I have from the add-on

> 13:51:32 fail: SwitchBotMqttApp.Services.MqttCoreService[0] subscribe action F1591E9D60F8,{   "CommandType": "command",   "Command": "createKey",   "ParamName": "btn",   "ParamValue": "action" } System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int64'.    at SwitchBotMqttApp.Services.MqttCoreService.<>c__DisplayClass17_1.<ReceiveCommandAsync>b__4(CommandPayloadDefinition paramDef) in C:\github\hsakoh\switchbot-mqtt\src\SwitchBotMqttApp\Services\MqttCoreService.cs:line 340    at System.Collections.Generic.List`1.ForEach(Action`1 action)    at SwitchBotMqttApp.Services.MqttCoreService.ReceiveCommandAsync(String payloadRaw, DeviceBase device) in C:\github\hsakoh\switchbot-mqtt\src\SwitchBotMqttApp\Services\MqttCoreService.cs:line 335

**Comment by hsakoh** [comment]
https://github.com/hsakoh/switchbot-mqtt/issues/5#issuecomment-1739029591
