### ISSUE TITLE
SwitchBot-Mqtt suddenly stopped working, nothing happens when attempting to fetch devices

### ISSUE THREAD

**Issue by DistractedPhysicist** [hsakoh/switchbot-mqtt#61]
Hi,

On my HA instance, I have been (mostly) successfully running the SwitchBot-Mqtt add-on for around 6 months now, but it seems to have stopped working sometime between tonight and last night (during which time I did not make any changes to my HA instance). 

I tried to uninstall and then reinstall the Mosquitto broker add-on, adding the corresponding Mqtt integration, and then finally reinstalling SwitchBot-Mqtt. After configuring the add-on exactly the same way as before (except setting both `UseWebhook` and `UseNgrok` to `false`)  and starting it, I went to the UI and clicked "Fetch Devices by SwitchBotApi", but nothing happened. Here is what the log looked like:

`21:22:02 info: Microsoft.Hosting.Lifetime[14] Now listening on: http://[::]:8098
21:22:02 info: Microsoft.Hosting.Lifetime[14] Now listening on: http://[::]:8099
21:22:02 info: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down.
21:22:02 info: Microsoft.Hosting.Lifetime[0] Hosting environment: Production
21:22:02 info: Microsoft.Hosting.Lifetime[0] Content root path: /app
21:22:16 info: SwitchBotMqttApp.Logics.DeviceConfigurationManager[0] device configuration file missing.
21:22:18 trce: SwitchBotMqttApp.Logics.SwitchBotApiClient[0] Send GET,devices,(null)
21:22:18 trce: SwitchBotMqttApp.Logics.SwitchBotApiClient[0] Response GET,https://api.switch-bot.com/v1.1/devices,{"message":"Forbidden"} 
21:22:18 fail: SwitchBotMqttApp.Logics.DeviceConfigurationManager[0] LoadDevicesAsync error. System.ApplicationException: {"message":"Forbidden"}     at SwitchBotMqttApp.Logics.SwitchBotApiClient.SendAndEnsureSuccessAsync[TBody](HttpRequestMessage requestMessage, CancellationToken cancellationToken, Int32[] additionalStatus, String bodyForLogging) in C:\github\hsakoh\switchbot-mqtt\src\SwitchBotMqttApp\Logics\SwitchBotApiClient.cs:line 140    at SwitchBotMqttApp.Logics.SwitchBotApiClient.GetDevicesAsync(CancellationToken cancellationToken) in C:\github\hsakoh\switchbot-mqtt\src\SwitchBotMqttApp\Logics\SwitchBotApiClient.cs:line 38    at SwitchBotMqttApp.Logics.DeviceConfigurationManager.LoadDevicesAsync(DevicesConfig currentData, CancellationToken cancellationToken) in C:\github\hsakoh\switchbot-mqtt\src\SwitchBotMqttApp\Logics\DeviceConfigurationManager.cs:line 60`

To my very inexperienced eyes, it looks like the SwitchBot API is denying access, but I double checked the API keys in my SwitchBot app and they are the same as before, so I do not understand why this would be. I was hoping you could provide me with some suggestions as to what might be going wrong. Here is some additional info about my setup (everything is latest):

SwitchBot-Mqtt version: 1.0.30
Mosquitto broker version: 6.4.1
HA instance details:
Core: 2024.12.3
Supervisor: 2024.11.4
Operating System: 14.0
Frontend: 20241127.8
Running on Raspberry Pi 5

Please let me know if you need any additional info! Many thanks in advance!

**Comment by sVnsation** [comment]
api.switch-bot.com is down: https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374

**Comment by sVnsation** [comment]
@hsakoh [Here](https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374#issuecomment-2545249154) it's mentioned to change to https://api.switchbot.net

**Comment by hsakoh** [comment]
https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374

The add-on version 1.0.31 has just been released.
This update allows the API base URL to be modified.
By default, it is set to `https://api.switch-bot.com/v1.1/` as specified in the documentation.
Temporarily changing it to `https://api.switchbot.net/v1.1/` is expected to resolve the issue.

Currently, `api.switch-bot.com` is a CNAME pointing to `api.switchbot.net.`
`api.switchbot.net` is a CNAME pointing to `d-isgqcucw72.execute-api.ap-northeast-1.amazonaws.com.`
 (This is an edge-optimized API endpoint provided by AWS API Gateway.)
 
The URL change should be reverted once the issue is resolved and should only be used as a temporary workaround for partial recovery.

**Comment by DistractedPhysicist** [comment]
Thank you for your fast response @hsakoh , I just got the add-on back up and running :)
