### ISSUE TITLE
Failed to save add-on configuration, Invalid list for option 'EnforceDeviceTypes

### ISSUE THREAD

**Issue by Lomok82** [hsakoh/switchbot-mqtt#7]
I'm trying to configure the add-on but it always show the following mesage:

Failed to save add-on configuration, Invalid list for option 'EnforceDeviceTypes' in SwitchBot-Mqtt (cafb8c58_switchbot_mqtt). Got {'Mqtt': {'AutoConfig': True, 'Host': '', 'Port': 1883, 'Id': '', 'Pw': '', 'Tls': False}, 'SwitchBot': {'ApiKey': 'redacted', 'ApiSecret': 'redacted'}, 'EnforceDeviceTypes': 'Hub',

I've tried using default value of null, NULL and also tried using "hub" and "hub 2" but still the message is the same.

Am i missing something?

**Comment by hsakoh** [comment]
Please try entering it on the YAML input screen in the following format.
`EnforceDeviceTypes: []`
![image](https://github.com/hsakoh/switchbot-mqtt/assets/20980395/e0ae69b6-9a10-45d0-a24d-6766e7c8c839)

Essentially, it is a forced override when there is no DeviceType response in the API, such as Curtain 3.
Reference: https://github.com/hsakoh/switchbot-mqtt/issues/3#issuecomment-1712718641

**Comment by Lomok82** [comment]
Thanks for the quick response!!! You are awesome!!!!
I was able to save the configuration after changing that line and i'm able to discover the devices now.

Thanks!!
