### ISSUE TITLE
Invalid list for option 'EnforceDeviceTypes' in SwitchBot-Mqtt

### ISSUE THREAD

**Issue by jgassens** [hsakoh/switchbot-mqtt#9]
Having followed the installation instructions, it won't let me save the configuration file. I get the following error:

> Failed to save add-on configuration, Invalid list for option 'EnforceDeviceTypes' in SwitchBot-Mqtt (cafb8c58_switchbot_mqtt). Got {'Mqtt': {'AutoConfig': True, 'Host': '', 'Port': 1883, 'Id': '', 'Pw': '', 'Tls': False}, 'SwitchBot': {'ApiKey': '', 'ApiSecret': ''}, 'EnforceDeviceTypes': None, 'WebhookService': {'UseWebhook': False, 'UseNgrok': True, 'NgrokAuthToken': '2ZuUp6tg5C4DCGztQa9GQdzdo7u_cSNkL1EqN8kV6WrcR3eN', 'HostUrl': '<Configuration required only when using Webhook without ngrok>'}, 'AutoStartServices': False, 'LogLevel': 'Trace'

From the install instructions, it looks like this can be left blank. I have pretty much the default config file (removed API specific info below). But it won't let me save!

<img width="1022" alt="Screenshot 2023-12-22 at 1 03 20 PM" src="https://github.com/hsakoh/switchbot-mqtt/assets/104028936/4263da8f-26d8-4b88-b13a-53983f32a0c9">

**Comment by hsakoh** [comment]
Please try entering it on the YAML input screen in the following format.
`EnforceDeviceTypes: []`
![image](https://github.com/hsakoh/switchbot-mqtt/assets/20980395/e0ae69b6-9a10-45d0-a24d-6766e7c8c839)

https://github.com/hsakoh/switchbot-mqtt/issues/7#issuecomment-1769575130

**Comment by jgassens** [comment]
perfect. thanks.
